name: Deploy to Coolify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deployment
        run: |
          curl -X GET \
            "https://coolify.farimani.se/api/v1/deploy?uuid=fwogwko8wcogs0gkscosog0k&force=false" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
